build(deps): bump @keplr-wallet/types from 0.10.19 to 0.11.17
desmos-labs/desmjs pull request #107
Opened 2022-11-24 07:42 UTC by dadamu

## Description
This PR bumps  @keplr-wallet/types from 0.10.19 to 0.11.17 and fix the break change.
Forwarding: #91 
Closes: #91

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] targeted the correct branch (see [PR Targeting](https://github.com/desmos-labs/desmjs/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] confirmed that this PR does not change production code

2022-11-24 14:57 UTC, manu0466 requested changes

2022-11-24 14:57 UTC, manu0466 commented on packages/keplr/src/chains.ts
>      feeCurrencies: chain.feeCurrencies,
```suggestion
    feeCurrencies: {
      ...chain.feeCurrencies,
      gasPriceStep: DesmosGasPriceStep,
    },
```
The `gasPriceStep` has been moved inside the `feeCurrencies` field you can see the doc [here](https://docs.keplr.app/api/suggest-chain.html).

2022-11-24 14:57 UTC, manu0466 commented on packages/keplr/src/chains.ts
> -  DesmosGasPriceStep,
Remember to reimport `DesmosGasPriceStep`

2022-11-25 17:01 UTC, manu0466 approved these changes
LGTM

2022-11-25 17:46 UTC, RiccardoM approved these changes
utACK

2022-11-25 17:48 UTC, merged